version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
